name: Fetch agenda from Google Calendar

on:
  schedule:
    - cron: '11 5 * * *'

env:
  TZ: "Europe/Warsaw"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set the Oauth token
      env:
        GCALCLI_OAUTH: ${{ secrets.GCALCLI_OAUTH }}
      run: echo $GCALCLI_OAUTH > /home/runner/.gcalcli_oauth

    - name: Fetch calendar
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        DEFAULT_CALENDAR: ${{ secrets.DEFAULT_CALENDAR }}
      run: |
        gcalcli \
          --client-id="$CLIENT_ID" \
          --client-secret="$CLIENT_SECRET" \
          --noauth_local_webserver \
          --default-calendar="$DEFAULT_CALENDAR" \
          --nocolor \
          --locale=pl_PL \
          agenda | tee agenda.txt

    - name: Fetch weather
      run: wget "https://www.yr.no/en/content/2-3081368/meteogram.svg"

    - name: Render image
      run: python main.py

    - name: Upload image
      uses: actions/upload-artifact@v2
      with:
        name: agenda
        path: agenda.png

    - name: Commit image
      run: |
        git config --global user.name 'Action Bot'
        git config --global user.email 'actionbot@noreply.com'
        git add agenda.png
        git commit --amend --no-edit
        git push --force